# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-webhook
  namespace: tekton-pipelines
spec:
  params:
  - description: The external domain for the EventListener e.g. `$(params.EventListenerName).<PROXYIP>.nip.io`
    name: ExternalDomain
    type: string
  - description: The GitHub user
    name: GitHubUser
    type: string
  - description: The GitHub repo where the webhook will be created
    name: GitHubRepo
    type: string
  - description: The GitHub organization where the webhook will be created
    name: GitHubOrg
    type: string
  - description: The Secret name for GitHub access token. This is always mounted and
      must exist
    name: GitHubSecretName
    type: string
  - description: The GitHub access token key name
    name: GitHubAccessTokenKey
    type: string
  - description: The GitHub secret string key name
    name: GitHubSecretStringKey
    type: string
  - default: github.com
    description: The GitHub domain. Override for GitHub Enterprise
    name: GitHubDomain
    type: string
  - default: '[\"push\",\"pull_request\"]'
    description: List of events the webhook will send notifications for
    name: WebhookEvents
    type: string
  steps:
  - args:
    - -ce
    - |
      set -e
      echo "Create Webhook"
      if [ $(params.GitHubDomain) = "github.com" ];then
        curl -v -d "{\"name\": \"web\",\"active\": true,\"events\": $(params.WebhookEvents),\"config\": {\"url\": \"http://$(params.ExternalDomain)\",\"content_type\": \"json\",\"insecure_ssl\": \"1\" ,\"secret\": \"$(cat /var/secret/$(params.GitHubSecretStringKey))\"}}" -X POST -u $(params.GitHubUser):$(cat /var/secret/$(params.GitHubAccessTokenKey)) -L https://api.github.com/repos/$(params.GitHubOrg)/$(params.GitHubRepo)/hooks
      else
        curl -d "{\"name\": \"web\",\"active\": true,\"events\": $(params.WebhookEvents),\"config\": {\"url\": \"http://$(params.ExternalDomain)/\",\"content_type\": \"json\",\"insecure_ssl\": \"1\" ,\"secret\": \"$(cat /var/secret/$(params.GitHubSecretStringKey))\"}}" -X POST -u $(params.GitHubUser):$(cat /var/secret/$(params.GitHubAccessTokenKey)) -L https://$(params.GitHubDomain)/api/v3/repos/$(params.GitHubOrg)/$(params.GitHubRepo)/hooks
      fi
    command:
    - sh
    image: curlimages/curl:latest
    name: create-webhook
    resources: {}
    volumeMounts:
    - mountPath: /var/secret
      name: github-secret
  volumes:
  - name: github-secret
    secret:
      secretName: $(params.GitHubSecretName)
